apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: inetplace
  name: inetplace-2
spec:
  containers:
  - image: nginx
    name: inetplace
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}